### ISSUE TITLE
Support `testdouble` without a global

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-cli-chai#28]
`ember-cli-testdouble` just updated to import `testdouble` through NPM Instead of Bower. This is great, but `td` is no longer a global, so the `vendor/chai-plugin-support/testdouble-chai.js` file no longer works.

How can we modify that file and import it into the build so that a "regular" Ember import will work?  Instead of this:

```js
(function() {
  chai.use(tdChai(td));
})();
```

we want to do this:

```js
import chai from 'chai'
import tdChai from 'testdouble-chai';
import td from 'testdouble';

chai.use(tdChai(td));
```

I tried just changing the file contents to import the dependency, but it's not actually processed correctly to change the ES6 style import into whatever Ember actually uses at runtime.  Any ideas on how to pull this off correctly?

**Comment by alexlafroscia** [comment]
`tdChai` actually supports being imported as an unnamed AMD module as well, so it would be great to import it the "right" way as well instead of relying on the global.

**Comment by alexlafroscia** [comment]
I was thinking we could add an `exports` property, to show that the file is an ES6 module, but technically nothing imports this file. It's just expected to be included and run automatically, which doesn't play nicely with importing a module.

**Comment by Turbo87** [comment]
@alexlafroscia I guess we need to add some logic to that file that figures out how to get a reference to the `testdouble` library. if it's available on `window` we can just take that, otherwise we'll have to see if we can import it in some way. you could try to `try { let td = require('testdouble'); } catch (error) { ... }` to import the AMD module, but we'd have to make sure that `testdouble` is included in the output file before our support file. 🤔

**Comment by alexlafroscia** [comment]
Alright, I'll give using `require` a shot. Because `ember-cli-testdouble` is going to import it into Ember as an AMD module, it shouldn't be available on the global at all... Which is good, except when it's not 😅
